#!/bin/bash
# Title:        Physical Pomodoro
# Description:  Hardware-level distraction blocker for 25-minute focus sprints.
# Net Mode:     BRIDGE

function run_pomodoro() {
    NETMODE BRIDGE
    sleep 10
    
    while true; do
        # Ready state
        LED SETUP
        
        # Wait for user to push the button to start the focus sprint
        NO_LED=true BUTTON
        
        # Focus Mode Active (Solid Red)
        LED R SOLID
        
        # Insert iptables rules to drop traffic containing specific strings
        iptables -I FORWARD -m string --algo bm --string "reddit.com" -j DROP
        iptables -I FORWARD -m string --algo bm --string "youtube.com" -j DROP
        iptables -I FORWARD -m string --algo bm --string "twitter.com" -j DROP
        iptables -I FORWARD -m string --algo bm --string "facebook.com" -j DROP
        
        # Sleep for 25 minutes (1500 seconds)
        sleep 1500
        
        # Break Time! (Solid Green)
        LED G SUCCESS
        
        # Remove the firewall blocks so you can browse again
        iptables -F FORWARD
        
        # 5 minute break (300 seconds) before resetting to the Ready state
        sleep 300
    done
}

USB_WAIT
run_pomodoro &
wait
