#!/bin/bash
# Title:        Hotel Stealth NAT
# Description:  Clones your MAC address and acts as a router for multiple devices.
# Net Mode:     NAT

function run_hotel_nat() {
    # Start in NAT mode (Squirrel acts as a router)
    NETMODE NAT
    sleep 10
    LED SETUP

    # Wait for button press to capture your laptop's MAC address and clone it
    NO_LED=true BUTTON
    LED SPECIAL
    
    # Grab the MAC address of the device plugged into the Squirrel's LAN port
    CLIENT_MAC=$(ip neigh show dev eth1 | awk '{print $5}' | head -n 1)
    
    if [ ! -z "$CLIENT_MAC" ]; then
        # Take the WAN interface down, spoof the MAC, and bring it back up
        ifconfig eth0 down
        macchanger -m "$CLIENT_MAC" eth0
        ifconfig eth0 up
        
        # Success - You can now plug a switch/AP into the Squirrel
        LED G SUCCESS
    else
        # Failed to find a client MAC
        LED FAIL
    fi
}

run_hotel_nat &
